export const Players = {
  blakeShaw: {
    name: "Blake Shaw",
    firstName: "Blake",
    hasPitched: false,
    hasSat: false,
  },
  brysonAhlstedt: {
    name: "Bryson Ahlstedt",
    firstName: "Bryson",
    hasPitched: false,
    hasSat: false,
  },
  carterBrooks: {
    name: "Carter Brooks",
    firstName: "Carter",
    hasPitched: false,
    hasSat: false,
  },
  jackVautour: {
    name: "Jack Vautour",
    firstName: "Jack",
    hasPitched: false,
    hasSat: false,
  },
  jasonMacPhearson: {
    name: "Jason MacPhearson",
    firstName: "Jason",
    hasPitched: false,
    hasSat: false,
  },
  johnStewart: {
    name: "John Stewart",
    firstName: "John",
    hasPitched: false,
    hasSat: false,
  },
  matthewShortt: {
    name: "Matthew Shortt",
    firstName: "Matthew",
    hasPitched: false,
    hasSat: false,
  },
  michaelBoyd: {
    name: "Michael Boyd",
    firstName: "Michael",
    hasPitched: false,
    hasSat: false,
  },
  ostopMostowy: {
    name: "Ostop Mostowy",
    firstName: "Ostop",
    hasPitched: false,
    hasSat: false,
  },
  philPavilic: {
    name: "Phil Pavilic",
    firstName: "Phil",
    hasPitched: false,
    hasSat: false,
  },
  ronanWeir: {
    name: "Ronan Weir",
    firstName: "Ronan",
    hasPitched: false,
    hasSat: false,
  },
  ryanShortt: {
    name: "Ryan Shortt",
    firstName: "Ryan",
    hasPitched: false,
    hasSat: false,
  },
  spencerDobbs: {
    name: "Spencer Dobbs",
    firstName: "Spencer",
    hasPitched: false,
    hasSat: false,
  },
  tylerVerbanac: {
    name: "Tyler Verbanac",
    firstName: "Tyler",
    hasPitched: false,
    hasSat: false,
  },
  zachCowan: {
    name: "Zach Cowan",
    firstName: "Zach",
    hasPitched: false,
    hasSat: false,
  },
};

export const Positions = [
  { label: "Pitcher", id: "pitcher" },
  { label: "Catcher", id: "catcher" },
  { label: "Short Stop", id: "shortStop" },
  { label: "First Base", id: "firstBase" },
  { label: "Second Base", id: "secondBase" },
  { label: "Third Base", id: "thirdBase" },
  { label: "Left Field", id: "leftField" },
  { label: "Center Field", id: "centerField" },
  { label: "Right Field", id: "rightField" },
  { label: "Rover", id: "rover" },
];
